### ISSUE TITLE
Allow entering a hardcoded octoprint address, instead of relying on auto-discovery

### ISSUE THREAD

**Issue by cscott** [scotthraban/octoprint-printer-connection-plugin-for-cura#3]
This would let you print to a remote printer (one which is not on your local network).

**Comment by scotthraban** [comment]
I have added an external configuration file where the plugin stores it settings. In this configuration file, you can turn discovery on/off, and you can also manually add a server, so that discovery is not needed. The API Key can also not be added in the configuration file, instead of in the source code. The configuration file is reloaded when changed, so no restart of Cura is required.
